language: ruby
rvm:
  - 2.7.3
services:
  - postgresql
before_install:
  - gem install bundler
before_script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - bundle exec rake db:create
  - bundle exec rake db:schema:load