version: 2.1

executors:
  default:
    working_directory: ~/hix_postgresql
    docker:
      - image: circleci/ruby:2.7.3
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLE_RETRY: 3
          BUNDLER_VERSION: 2.0.1
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          PG_HOST: 127.0.0.1
          PGUSER: postgres
      - image: circleci/postgres:12.0
        environment:
          POSTGRES_DB: classfied_postgresql_test
          POSTGRES_USER: postgres

commands:
  configure_bundler:
    description: Configure bundler
    steps:
      - run:
          name: Configure bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - hix_postgresql-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - hix_postgresql-
      - configure_bundler
      - run:
          name: Install bundle
          command: bundle install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m
      - run:
          name: Setup DB
          command: bundle exec rails db:create db:migrate db:schema:load --trace
      - save_cache:
          key: hix_postgresql-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: ~/
          paths:
            - ./hix_postgresql
  rspec:
    executor: default
    parallelism: 4
    steps:
      - attach_workspace:
          at: ~/
      - configure_bundler
      - run:
          name: Create test database
          command: bundle exec rake db:migrate RAILS_ENV=test
      - run:
          name: split spec
          command: circleci tests glob "spec/**/*.rb" | circleci tests split > /tmp/tests-to-run
      - run:
          name: Run spec 
          command: CIRCLE_NODE_INDEX=3 CIRCLE_NODE_TOTAL=4 bundle exec rspec $(cat /tmp/tests-to-run)
      - store_artifacts:
          path: coverage
  rubocop:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - configure_bundler
      - run:
          name: Rubocop
          command: bundle exec rubocop app
  brakeman:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - configure_bundler
      - run:
          name: Brakeman
          command: bundle exec brakeman
  fasterer:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - configure_bundler
      - run:
          name: Fasterer
          command: bundle exec fasterer
workflows:
  version: 2
  integration:
    jobs:
      - build
      - rubocop:
          requires:
            - build
      - rspec:
          requires:
            - build
      - brakeman:
          requires:
            - build

